---
apiVersion: v1
kind: Secret
metadata:
  name: tap-crd-overlay
  namespace: tanzu-packages
stringData:
  add-crd-support.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "prometheus-kube-state-metrics", "namespace": "tanzu-system-monitoring"}}),expects="1+"
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by=overlay.subset({"name": "prometheus-kube-state-metrics"}), expects="1+"
            -
              #@overlay/match missing_ok=True
              args:
                - --custom-resource-state-config
                -  |
                    spec:
                      resources:
                        - groupVersionKind:
                            group: carto.run
                            version: v1alpha1
                            kind: Workload
                          labelsFromPath:
                            name: 
                            - metadata
                            - name
                            namespace:
                            - metadata
                            - namespace
                          metrics:
                            - name: info
                              help: Information about a clusterclass.
                              each:
                                info:
                                  # TODO: added metadata.name even it's already defined above as the metric doesn't work with empty labelsFromPath.
                                  labelsFromPath:
                                    name:
                                    - metadata
                                    - name
                                type: Info
                            - name: created
                              help: Unix creation timestamp.
                              each:
                                gauge:
                                  path:
                                  - metadata
                                  - creationTimestamp
                                type: Gauge
                            - name: status_condition
                              help: The condition of a workload.
                              each:
                                stateSet:
                                  labelName: status
                                  labelsFromPath:
                                    type:
                                    - type
                                  list:
                                  - 'True'
                                  - 'False'
                                  - Unknown
                                  path:
                                  - status
                                  - conditions
                                  valueFrom:
                                  - status
                                type: StateSet
